#cloud-config
hostname: nginx-lb-01
package_update: true
package_upgrade: true
packages:
  - curl
  - gnupg2
  - ca-certificates
  - lsb-release
  - ubuntu-keyring
write_files:
  - path: /etc/nginx/nginx.conf
    content: |
      user www-data;
      worker_processes auto;
      pid /run/nginx.pid;
      include /etc/nginx/modules-enabled/*.conf;
      events {
          worker_connections 768;
      }
      http {
          sendfile on;
          tcp_nopush on;
          types_hash_max_size 2048;
          include /etc/nginx/mime.types;
          default_type application/octet-stream;
          ssl_protocols TLSv1 TLSv1.1 TLSv1.2 TLSv1.3;
          ssl_prefer_server_ciphers on;
          access_log /var/log/nginx/access.log;
          error_log /var/log/nginx/error.log;
          gzip on;
          include /etc/nginx/conf.d/*.conf;
          include /etc/nginx/sites-enabled/*;

          upstream aspire_dashboard_backend {
              server 172.16.16.96:30888;
              server 172.16.16.103:30888;
              server 172.16.16.104:30888;
          }

          server {
              listen 18888;
              location / {
                  proxy_pass http://aspire_dashboard_backend;
                  proxy_set_header Host $host;
                  proxy_set_header X-Real-IP $remote_addr;
                  proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
                  proxy_set_header X-Forwarded-Proto $scheme;
              }
          }
      }
      stream {
          upstream sql_backend {
            server 172.16.16.96:31432;
            server 172.16.16.103:31432;
            server 172.16.16.104:31432;
          }
        server {
            listen 1433;
            proxy_pass sql_backend;
        }
          upstream redis_backend {
              server 172.16.16.96:30379;
              server 172.16.16.103:30379;
              server 172.16.16.104:30379;
          }
          server {
              listen 6379;
              proxy_pass redis_backend;
          }

          upstream rabbitmq_amqp_backend {
              server 172.16.16.96:31302;
              server 172.16.16.103:31302;
              server 172.16.16.104:31302;
          }
          server {
              listen 5672;
              proxy_pass rabbitmq_amqp_backend;
          }
          
          upstream rabbitmq_mgmt_backend {
              server 172.16.16.96:30934;
              server 172.16.16.103:30934;
              server 172.16.16.104:30934;
          }
          server {
              listen 15672;
              proxy_pass rabbitmq_mgmt_backend;
          }

          upstream aspire_otlp_backend {
              server 172.16.16.96:30317;
              server 172.16.16.103:30317;
              server 172.16.16.104:30317;
          }
          server {
              listen 4317;
              proxy_pass aspire_otlp_backend;
          }
      }
  - path: /etc/apt/preferences.d/99nginx
    content: |
      Package: *
      Pin: origin nginx.org
      Pin: release o=nginx
      Pin-Priority: 900
users:
  - name: chris
    sudo: ALL=(ALL) NOPASSWD:ALL
    groups: users, admin
    shell: /bin/bash
    ssh_authorized_keys:
      - ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIN9XgomGsuLPyyGdQpAIK52I1hdkYNWETl7qglcRzq2e
runcmd:
  - curl https://nginx.org/keys/nginx_signing.key | gpg --dearmor | sudo tee /usr/share/keyrings/nginx-archive-keyring.gpg >/dev/null
  - echo "deb [signed-by=/usr/share/keyrings/nginx-archive-keyring.gpg] http://nginx.org/packages/ubuntu `lsb_release -cs` nginx" | sudo tee /etc/apt/sources.list.d/nginx.list
  - sudo apt update
  - sudo apt install -y nginx
  - sudo systemctl start nginx
  - sudo nginx -t
  - sudo systemctl restart nginx
